version: '3.7'

services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.2
    container_name: laravel-db
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=laravel
      - MARIADB_DATABASE=laravel_db
      - MARIADB_PASSWORD=my_password
    logging:
      driver: "local"
      options:
        max-size: "200k"
        max-file: "10"

  myapp:
    tty: true
    image: docker.io/bitnami/laravel:5.8.35
    container_name: laravel
    environment:
      - DB_HOST=mariadb
      - DB_USERNAME=laravel
      - DB_DATABASE=laravel_db
      - DB_PASSWORD=my_password
    depends_on:
      - mariadb
    logging:
      driver: "local"
      options:
        max-size: "200k"
        max-file: "10"
    user: "1001"
    volumes:
      - ./app:/app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.test.rule=Host(`laravel.${FQDN:-handlemycomplaint.com.au}`)"
      - "traefik.http.routers.test.entrypoints=websecure"
      - "traefik.http.routers.test.tls.certresolver=hmcresolver"
      - "traefik.http.routers.test.tls.domains[0].main=${FQDN:-handlemycomplaint.com.au}"
      - "traefik.http.routers.test.tls.domains[0].sans=*.${FQDN:-handlemycomplaint.com.au}"



networks:
  default:
    external:
      name: hmc

